### ISSUE TITLE
Investigate telemetry options to capture useful metrics

### ISSUE THREAD

**Issue by riweston** [cloudreach/gcp-pubsub-acloudguru#10]
## Overview
Its important that we capture telemetry information from the Cloud functions in the solution to enable troubleshooting

## Tasks

1. Explore Cloud Trace to instrument the Cloud Functions in the first instance using OpenTelemetry as it is actively in development.

- [OpenTelemetry](https://cloud.google.com/trace/docs/setup/go-ot)

2. Provide some demonstration code for an example Cloud Function
3. Sample dashboard to show telemetry
4. Provide some recommendations for what to monitor on the Cloud Functions

For example
- Track the latency of the JSON POST request
- Track the time it took to process the request
- Track the time it took to publish the batch message to the PubSub
- Track the overall throughput of the cloud function
- Track any custom metrics you may want to monitor
- Track any errors that may occur during the function execution
- Track processing a batch message onto a pubsub, size, topic, ID
- Track reading messages from the batch, size of batch, topic, ID
- Track POST request, time to make the request, payload size, URL of the API, HTTP status code

## Acceptance Criteria
- [ ] Clear picture of what to Trace
- [ ] Clear picture of when and where to log and whether we need any custom spans
- [ ] Dashboard clarity of error logs

**Comment by riweston** [comment]
I had a chat with our colleagues to review where to go with and Firestore was suggested to capture this data on an ongoing basis.

Useful fields that I think that we should capture longterm as usage statistics;

- Time of event
- User activated
- User(s) deactivated
- Users activated at the time of request including their last login time
